### ISSUE TITLE
Auth with facebook is not working anymore

### ISSUE THREAD

**Issue by GoogleCodeExporter** [manieyedone85/socialauth-android#52]
```
What steps will reproduce the problem?
1. Download socialauth-android-sdk-2.0.zip
2. Import any of the test projects
3. Try to login using facebook

What is the expected output? What do you see instead?
It suppose to get the "Authentication Successful" log from the ResponseListener 
but what i get is the following exception:

04-12 21:07:46.510: W/System.err(7078): 
org.brickred.socialauth.exception.SocialAuthException: Verification code is null
04-12 21:07:46.510: W/System.err(7078):     at 
org.brickred.socialauth.oauthstrategy.OAuth2.verifyResponse(OAuth2.java:114)
04-12 21:07:46.510: W/System.err(7078):     at 
org.brickred.socialauth.oauthstrategy.OAuth2.verifyResponse(OAuth2.java:102)
04-12 21:07:46.510: W/System.err(7078):     at 
org.brickred.socialauth.provider.FacebookImpl.doVerifyResponse(FacebookImpl.java
:164)
04-12 21:07:46.510: W/System.err(7078):     at 
org.brickred.socialauth.provider.FacebookImpl.verifyResponse(FacebookImpl.java:1
54)
04-12 21:07:46.510: W/System.err(7078):     at 
org.brickred.socialauth.SocialAuthManager.connect(SocialAuthManager.java:183)
04-12 21:07:46.510: W/System.err(7078):     at 
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$1.run(S
ocialAuthDialog.java:244)
04-12 21:07:46.510: W/System.err(7078):     at 
java.lang.Thread.run(Thread.java:856)
04-12 21:07:46.510: W/InputMethodManagerService(519): Window already focused, 
ignoring focus gain of: 
com.android.internal.view.IInputMethodClient$Stub$Proxy@420ef600 
attribute=android.view.inputmethod.EditorInfo@4206f4a0, token = 
android.os.BinderProxy@41ff3268
04-12 21:07:46.520: D/SocialAuthError(7078): 
org.brickred.socialauth.exception.SocialAuthException: Verification code is null
04-12 21:07:46.520: W/System.err(7078): 
org.brickred.socialauth.android.SocialAuthError: Unknown Error
04-12 21:07:46.520: W/System.err(7078):     at 
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$1.run(S
ocialAuthDialog.java:264)
04-12 21:07:46.520: W/System.err(7078):     at 
java.lang.Thread.run(Thread.java:856)
04-12 21:07:46.520: D/LifeView(7078): Unknown Error


What version of the product are you using? On what operating system?
I'm using the socialauth-android-sdk-2.0 and this behavior was present testing 
with an Android 4.2.2 and Android 2.3.3 devices.

Please provide any additional information below.
I test 1 week ago with exactly the same code and now it's not working.
```

Original issue reported on code.google.com by `victor.c...@gmail.com` on 12 Apr 2013 at 7:10

**Comment by GoogleCodeExporter** [comment]
```
I got the same error today with two different devices. The authentication  
keeps faling...
```

Original comment by `dharm82...@gmail.com` on 13 Apr 2013 at 6:50

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi , we have checked number of times with different keys but facebook is 
working fine.

Please let us know are you still facing the issue ? 
```

Original comment by `vineet.a...@3pillarglobal.com` on 14 Apr 2013 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
Have the same issue. I test my APP 10 of April and works fine. Today get the 
error "Verefication code is null".
I download the examples "share-button" and "share-bar" and I have the same 
problem with Facebook.
```

Original comment by `francisc...@gmail.com` on 16 Apr 2013 at 9:06

**Comment by GoogleCodeExporter** [comment]
```
In the log I get this:
04-16 11:20:53.530: D/SocialAuth-WebView(17922): Override url: 
fbconnect://success#access_token=BAAHJpLUSchsBAIrBSL0E1z3pQVMtCz7lp86TMygUgnSSjy
a7nd5w05pSFcuebxsmFPndjoCz6z56pkLMG2FbFBlahBlahBlah&expires_in=5180716

I dont know, but the parameter change from "code" to "acces_token"
```

Original comment by `francisc...@gmail.com` on 16 Apr 2013 at 9:27

**Comment by GoogleCodeExporter** [comment]
```
I am too facing the same issue. Did anyone get a solution?
```

Original comment by `bhargavs...@gmail.com` on 17 Apr 2013 at 7:11

**Comment by GoogleCodeExporter** [comment]
```
I have the same problem.
I have posted a question on stack overflow too but no answer yet. 
http://stackoverflow.com/questions/15986651/socialauth-android-authorization-suc
cessfull-with-facebook-but-verification-code
```

Original comment by `renato.d...@gmail.com` on 17 Apr 2013 at 7:55

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I am too facing the same issue.Please let us know the solution
```

Original comment by `vinaydre...@gmail.com` on 18 Apr 2013 at 5:29

**Comment by GoogleCodeExporter** [comment]
```
Hi ,

We are looking to provide a solution today. Thanks for patience.

```

Original comment by `vineet.a...@3pillarglobal.com` on 18 Apr 2013 at 6:38

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Same with me.... waiting for a fix. Good luck
```

Original comment by `javier.r...@gmail.com` on 18 Apr 2013 at 3:31

**Comment by GoogleCodeExporter** [comment]
```
Eagerly waiting for the solution? Shall I know the status?
```

Original comment by `bhargavs...@gmail.com` on 18 Apr 2013 at 5:24

**Comment by GoogleCodeExporter** [comment]
```
Same here!
```

Original comment by `raf...@telethrive.com` on 19 Apr 2013 at 12:33

**Comment by GoogleCodeExporter** [comment]
```
I have the same error! Can't use facebook. Tested on socialauth-android-sdk-2.1.
```

Original comment by `chistovskis` on 21 Apr 2013 at 4:55

**Comment by GoogleCodeExporter** [comment]
```
Hi , Please find a zip file with new jars to test. 

Facebook has done api changes and we are following it. Please note that its is 
not a final jar. After login , you will get a screen " you are already 
authorized" , then pressing ok , you will be connected.
```

Original comment by `vineet.a...@3pillarglobal.com` on 22 Apr 2013 at 5:12
- Changed state: **Accepted**
- Added labels: **Type-Review**
- Removed labels: **Type-Defect**

Attachments:
- [jars.rar](https://storage.googleapis.com/google-code-attachments/socialauth-android/issue-52/comment-17/jars.rar)

**Comment by GoogleCodeExporter** [comment]
```
I can confirm the new jars posted here works. Thanks guys!
```

Original comment by `gilosmic...@gmail.com` on 22 Apr 2013 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
I can also confirm. It's possible to use facebook again. Thanks!
```

Original comment by `chistovskis` on 22 Apr 2013 at 6:05

**Comment by GoogleCodeExporter** [comment]
```
I have confirmed that now the authentication is working but i have tried again 
with the share-button project in order to send a post to facebook and i 
received the following error:

04-22 10:13:25.919: I/FacebookImpl(6172): Updating status : test!!! 123
04-22 10:13:26.019: D/overlay(158): Unset pipe=VG0 dpy=0; Unset pipe=VG1 dpy=0; 
Unset pipe=RGB1 dpy=0; 
04-22 10:13:26.639: D/SocialAuthError(6172): 
org.brickred.socialauth.exception.SocialAuthException: 
org.brickred.socialauth.exception.SocialAuthException: Status not updated. 
Return Status code :400
04-22 10:13:26.639: D/ShareButton(6172): Authentication Error: Message Not 
Posted
```

Original comment by `victor.c...@gmail.com` on 22 Apr 2013 at 8:16

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hi....
     Mr, i done fb posting ,but on twitter i hav problems.. i attached screen shot below,,after login twitter page is on front,,,i m not getting "Twitter  Connected" msg,i m tried so...bt no one is working...
i hope u,,giv sol to me.. thank you..
```

Original comment by `a.an...@quadrupleindia.com` on 22 Apr 2013 at 12:40

Attachments:
- [twitter error.png](https://storage.googleapis.com/google-code-attachments/socialauth-android/issue-52/comment-22/twitter error.png)

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
 jars.rar 
 214 KB   Download 
Yes Its really working with new Jars, I was trying since morning, Its Done,  
Thanks a lot :) Good Work.
```

Original comment by `khurram....@gmail.com` on 22 Apr 2013 at 1:36

**Comment by GoogleCodeExporter** [comment]
```
Good job! 
When do you expect to relase the code of this fix?

Thanks
```

Original comment by `javier.r...@gmail.com` on 23 Apr 2013 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
Thanks..
This work fine..Thanks a lott..

```

Original comment by `ansh...@gmail.com` on 24 Apr 2013 at 5:07

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Hello vineet... your answer is perfect ... thanks alot....:)
```

Original comment by `ishas...@gmail.com` on 24 Apr 2013 at 12:40

**Comment by GoogleCodeExporter** [comment]
```
It works fine on new androids, but :)
It has stopped working on android 2.2, I am having exception:

java.lang.NoSuchMethodError: javax.net.ssl.SSLContext.setDefault

If I remember correctly this issue was patched with this code submition one 
month ago: https://code.google.com/p/socialauth/issues/detail?id=252

Can you please upload source code or apply same patch again ?





```

Original comment by `slobodan...@gmail.com` on 24 Apr 2013 at 1:11

**Comment by GoogleCodeExporter** [comment]
```
hi victor, it seems you are trying to post message with special characters. we 
need to check.please open a new issue if unresolved

hi anand , i need to check. i think the issue should not be there. please open 
a new issue wuth full stack trace

javier , the office release would be after may 20.

slobodan , thanks will check this.
```

Original comment by `vineet.a...@3pillarglobal.com` on 25 Apr 2013 at 9:34

**Comment by GoogleCodeExporter** [comment]
```
Thanks a lot @17 vineet.a...@3pillarglobal.com.............You saved my whole 
day.......
:)

```

Original comment by `sufalamt...@gmail.com` on 26 Apr 2013 at 12:12

**Comment by GoogleCodeExporter** [comment]
```
after using jars...i m facing the problem in facebook,You have already 
authorized yourapp, verification code is null.... please tell me the 
solution...i  am sending u my code.. please find the attachment n reply me 
ASAP....thanx alot in advance...
```

Original comment by `khushbu....@gmail.com` on 30 Apr 2013 at 12:23

**Comment by GoogleCodeExporter** [comment]
Original comment by `khushbu....@gmail.com` on 30 Apr 2013 at 12:23

**Comment by GoogleCodeExporter** [comment]
```
I am using the 2.1 jar files and still having this problem with share-bar. 
org.brickred.socialauth.exception.SocialAuthException: Verification code is null

```

Original comment by `gen3soft...@gmail.com` on 8 May 2013 at 4:15

Attachments:
- [log.txt](https://storage.googleapis.com/google-code-attachments/socialauth-android/issue-52/comment-34/log.txt)

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I am able to post to linkedin fine but twitter and facebook fails.

Twitter Error I get as below:
-----------------------------
05-10 16:06:38.630: I/SocialAuthManager(10061): Connecting provider : twitter
05-10 16:06:38.630: I/TwitterImpl(10061): Verifying the authentication response 
from provider
05-10 16:06:38.630: I/OAuth1(10061): Verifying the authentication response from 
provider
05-10 16:06:41.080: W/System.err(10061): 
org.brickred.socialauth.exception.SocialAuthException: Unable to retrieve the 
access token. Status: 401
05-10 16:06:41.080: W/System.err(10061):    at 
org.brickred.socialauth.util.OAuthConsumer.getAccessToken(OAuthConsumer.java:269
)
05-10 16:06:41.080: W/System.err(10061):    at 
org.brickred.socialauth.oauthstrategy.OAuth1.verifyResponse(OAuth1.java:97)
05-10 16:06:41.080: W/System.err(10061):    at 
org.brickred.socialauth.oauthstrategy.OAuth1.verifyResponse(OAuth1.java:107)
05-10 16:06:41.080: W/System.err(10061):    at 
org.brickred.socialauth.provider.TwitterImpl.doVerifyResponse(TwitterImpl.java:1
67)
05-10 16:06:41.080: W/System.err(10061):    at 
org.brickred.socialauth.provider.TwitterImpl.verifyResponse(TwitterImpl.java:158
)
05-10 16:06:41.080: W/System.err(10061):    at 
org.brickred.socialauth.SocialAuthManager.connect(SocialAuthManager.java:183)
05-10 16:06:41.080: W/System.err(10061):    at 
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$1.run(S
ocialAuthDialog.java:243)
05-10 16:06:41.080: W/System.err(10061):    at 
java.lang.Thread.run(Thread.java:856)
05-10 16:06:41.080: D/SocialAuthError(10061): 
org.brickred.socialauth.exception.SocialAuthException: Unable to retrieve the 
access token. Status: 401


Facebook Exception as below:
----------------------------
05-10 16:02:12.460: D/SocialAuth-WebView(10061): 
onPageStart:https://m.facebook.com/dialog/oauth/write
05-10 16:02:13.070: D/SocialAuth-WebView(10061): Override url: 
fbconnect://success#access_token=CAAHdPiWKMJkBADClqSrGob9gCz1hPgQXXZC9RB3wVfT5J9
qNI0ZADZAjfsAzdfBH9pAYZCK5kClG7o9wH3HAIZC6rtJdiSZCT0YZBaJiiFr65cLThQX88s2zi7Y16Z
CqcFGjPNhrcpLfqQIC37nYl1LC&expires_in=5182194
05-10 16:02:13.090: I/SocialAuthManager(10061): Connecting provider : facebook
05-10 16:02:13.090: I/FacebookImpl(10061): Retrieving Access Token in verify 
response function
05-10 16:02:13.090: I/OAuth2(10061): Verifying the authentication response from 
provider
05-10 16:02:13.100: W/System.err(10061): 
org.brickred.socialauth.exception.SocialAuthException: Verification code is null
05-10 16:02:13.100: W/System.err(10061):    at 
org.brickred.socialauth.oauthstrategy.OAuth2.verifyResponse(OAuth2.java:114)
05-10 16:02:13.100: W/System.err(10061):    at 
org.brickred.socialauth.oauthstrategy.OAuth2.verifyResponse(OAuth2.java:102)
05-10 16:02:13.100: W/System.err(10061):    at 
org.brickred.socialauth.provider.FacebookImpl.doVerifyResponse(FacebookImpl.java
:164)
05-10 16:02:13.100: W/System.err(10061):    at 
org.brickred.socialauth.provider.FacebookImpl.verifyResponse(FacebookImpl.java:1
54)
05-10 16:02:13.100: W/System.err(10061):    at 
org.brickred.socialauth.SocialAuthManager.connect(SocialAuthManager.java:183)
05-10 16:02:13.100: W/System.err(10061):    at 
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$1.run(S
ocialAuthDialog.java:243)
05-10 16:02:13.100: W/System.err(10061):    at 
java.lang.Thread.run(Thread.java:856)
05-10 16:02:13.100: D/SocialAuthError(10061): 
org.brickred.socialauth.exception.SocialAuthException: Verification code is null



I am using socialauth-android-2.0.jar and socialauth-4.0.jar from 
socialauth-android-sdk-2.0.zip on windows 7 with java 1.6. 
```

Original comment by `indiami...@gmail.com` on 10 May 2013 at 10:45

**Comment by GoogleCodeExporter** [comment]
```
Try using the 2.1 jar above. It partially solved this problem for me, but for 
some reason only in the share button app. 
```

Original comment by `gen3soft...@gmail.com` on 10 May 2013 at 4:10

**Comment by GoogleCodeExporter** [comment]
```
Same error with twitter " Unable to retrieve the access token. Status: 401"
```

Original comment by `jrodrigu...@gmail.com` on 14 May 2013 at 3:25

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I need the source code with this fix 
Thank you 
```

Original comment by `bilal.el...@gmail.com` on 18 May 2013 at 4:42

**Comment by GoogleCodeExporter** [comment]
```
use 2.1 jar, and clean your project,. that's will fix facebook.
it's work for me:-)
```

Original comment by `Donik...@gmail.com` on 19 May 2013 at 3:19

**Comment by GoogleCodeExporter** [comment]
```
Hi , we are looking to release next version in next 2 weeks. In case you have 
any issues , requests please let us know. We will try to incorporate them.
```

Original comment by `vineet.a...@3pillarglobal.com` on 22 May 2013 at 11:01

**Comment by GoogleCodeExporter** [comment]
```
*Khushi Sharma..*
```

Original comment by `khushbu....@gmail.com` on 22 May 2013 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
i have issue in facebook


*Khushi Sharma..*


On Wed, May 22, 2013 at 4:33 PM, Khushbu Sharma
<khushbu.sharma92@gmail.com>wrote:
```

Original comment by `khushbu....@gmail.com` on 22 May 2013 at 11:04

**Comment by GoogleCodeExporter** [comment]
```
use 2.1 jar, and clean your project,. that's will fix facebook.
```

Original comment by `vineet.a...@3pillarglobal.com` on 22 May 2013 at 11:05

**Comment by GoogleCodeExporter** [comment]
```
i have done this thing...


*Khushi Sharma..*
```

Original comment by `khushbu....@gmail.com` on 22 May 2013 at 11:15

**Comment by GoogleCodeExporter** [comment]
```
Hi,

I tried 2.1 jar it lets me send to linkedin, twitter but not facebook.  I still 
get same exception as I reported earlier.

Regards,

Miten.
```

Original comment by `indiami...@gmail.com` on 23 May 2013 at 6:50

**Comment by GoogleCodeExporter** [comment]
```
this jar file work where u have bigger screen like any 7" tab, but screen size 
less then it not able to show UI component OK/CANCEL on FB authenticate page, 
it just display n went..at bottom(not visible) of layout, and since layout not 
scroll-able so u can's scroll it...any suggestion if any one faced similar 
problem..so if it's solved in any new version..please update here.

Thanks
```

Original comment by `shubhamP...@gmail.com` on 26 May 2013 at 8:07

**Comment by GoogleCodeExporter** [comment]
```
Hi gen3Software , the jars will work for all examples. you need to replace 
manually these jars in your share-button app.
```

Original comment by `vineet.a...@3pillarglobal.com` on 27 May 2013 at 8:19

**Comment by GoogleCodeExporter** [comment]
```
Hi indiamiten , 

try to clean your project and remove the app from the account you are testing 
and do fresh authentication.
```

Original comment by `vineet.a...@3pillarglobal.com` on 27 May 2013 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
Hi Shubham , 

we have tested this problem not exists. checked with s3 , s2 , galaxy Y. which 
device u are testing? if size is small the dialog will be scrollable.
```

Original comment by `vineet.a...@3pillarglobal.com` on 27 May 2013 at 8:23

**Comment by GoogleCodeExporter** [comment]
```
I checked with S3...it's just show "Your are already authorise" nothing at 
bottom side...but in Moto Zoom TAB it showing properly.
```

Original comment by `shubhamP...@gmail.com` on 27 May 2013 at 4:30

**Comment by GoogleCodeExporter** [comment]
```
here dialog is not showing scroll-able at all, OK/CANCEL button display for a 
while and went somewhere into layout which is not visible in case of small 
screen.
```

Original comment by `shubhamP...@gmail.com` on 28 May 2013 at 2:02

**Comment by GoogleCodeExporter** [comment]
```
Hi gen3Software , 
when i use the socialauth-4.0.jar and socialauth-android-2.1.jar which are 
launched on Apr 21, 2013, on facebook it`s just show "you are already 
authorise", but nothing else... see the log ,it returns the error message 
org.brickred.socialauth.exception.SocialAuthException: Error while getting 
profile from https://graph.facebook.com/me....
when I use the earlier socialauth-4.0.jar the error message is: Verification 
code is null
regards,
Aaron

```

Original comment by `ReyZhan...@gmail.com` on 28 May 2013 at 2:31

**Comment by GoogleCodeExporter** [comment]
```
Hi vineet,
you can see here in attachment...OK/Cancel not visible in this layout, nor this 
page is scroll-able. please provide your input/suggestion here.
```

Original comment by `shubhamP...@gmail.com` on 28 May 2013 at 3:01

Attachments:
- [auth_issue.png](https://storage.googleapis.com/google-code-attachments/socialauth-android/issue-52/comment-54/auth_issue.png)

**Comment by GoogleCodeExporter** [comment]
```
here we go see attachment, button are available at bottom. I run app on 
emulator and using TAB event able to shift control from one child view to 
another.

please fix it or let us know if have any suggestion here?
```

Original comment by `shub...@azoi.com` on 28 May 2013 at 10:31

Attachments:
- [b4.png](https://storage.googleapis.com/google-code-attachments/socialauth-android/issue-52/comment-55/b4.png)
- [aftr.png](https://storage.googleapis.com/google-code-attachments/socialauth-android/issue-52/comment-55/aftr.png)
- [ohh.png](https://storage.googleapis.com/google-code-attachments/socialauth-android/issue-52/comment-55/ohh.png)

**Comment by GoogleCodeExporter** [comment]
```
Hello team, any update/suggestion here regarding scrolling issue?
```

Original comment by `shubhamP...@gmail.com` on 29 May 2013 at 3:22

**Comment by GoogleCodeExporter** [comment]
```
Hi Shubham,

have u tried any changes in source code. We have checked on all acreen sizes 
and we are not getting any issue. ON all phones its working fine for us.


```

Original comment by `vineet.a...@3pillarglobal.com` on 30 May 2013 at 2:37

**Comment by GoogleCodeExporter** [comment]
```
I checked your source code..but for integration purpose I am directly using 
same jar provided by here...please check in any small screen device...you can 
see exactly same case with another guy who is directly using sdk provided by FB.

please check this also https://developers.facebook.com/bugs/525568624146255
```

Original comment by `shub...@azoi.com` on 30 May 2013 at 3:14

**Comment by GoogleCodeExporter** [comment]
```
any update on scrolling issue?
```

Original comment by `shubhamP...@gmail.com` on 4 Jun 2013 at 2:56

**Comment by GoogleCodeExporter** [comment]
```
I can't link facebook to app.s like words with friends .please help.
```

Original comment by `rustycfe...@gmail.com` on 7 Jun 2013 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
the latest jar is released. closing this pending issue. please open new issue 
for any problems. check examples for use.
```

Original comment by `l...@3pillarglobal.com` on 10 Jun 2013 at 3:20
- Changed state: **Fixed**
- Added labels: **Type-Defect**
- Removed labels: **Type-Review**

**Comment by GoogleCodeExporter** [comment]
```
Thank you so much..Scrolling issue got solved, but with authentication done it 
show "You are already authorize XXX"..can you people explain why this is 
for..and how it work. Thanks for all your effort :)
```

Original comment by `shubhamP...@gmail.com` on 12 Jun 2013 at 8:21

**Comment by GoogleCodeExporter** [comment]
```
I have added new jars to my application(servlet based)bot its still showing 
error that verification code is null for facebook authentication.
```

Original comment by `shrutik....@gmail.com` on 28 Jun 2013 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
I just noticed the issue while trying to login into facebook. Today 12:00 p.m. 
GMT. The log is from the latest attempt at 12:40 p.m.
06-28 12:40:32.661: W/System.err(813): 
org.brickred.socialauth.android.SocialAuthError: Unknown Error
06-28 12:40:32.661: W/System.err(813):  at 
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$1.run(S
ocialAuthDialog.java:265)
06-28 12:40:32.661: W/System.err(813):  at java.lang.Thread.run(Thread.java:856)


06-28 12:40:32.453: I/SocialAuthManager(813): Connecting provider : facebook
06-28 12:40:32.453: I/FacebookImpl(813): Retrieving Access Token in verify 
response function
06-28 12:40:32.554: I/OAuth2(813): Verifying the authentication response from 
provider
06-28 12:40:32.554: W/System.err(813): 
org.brickred.socialauth.exception.SocialAuthException: Verification code is null


06-28 12:40:32.554: W/System.err(813):  at 
org.brickred.socialauth.oauthstrategy.OAuth2.verifyResponse(OAuth2.java:136)
06-28 12:40:32.554: W/System.err(813):  at 
org.brickred.socialauth.oauthstrategy.OAuth2.verifyResponse(OAuth2.java:102)
06-28 12:40:32.592: W/System.err(813):  at 
org.brickred.socialauth.provider.FacebookImpl.doVerifyResponse(FacebookImpl.java
:188)
06-28 12:40:32.592: W/System.err(813):  at 
org.brickred.socialauth.provider.FacebookImpl.verifyResponse(FacebookImpl.java:1
78)
06-28 12:40:32.603: W/System.err(813):  at 
org.brickred.socialauth.SocialAuthManager.connect(SocialAuthManager.java:184)
06-28 12:40:32.603: W/System.err(813):  at 
org.brickred.socialauth.android.SocialAuthDialog$SocialAuthWebViewClient$1.run
```

Original comment by `dimitri....@gmail.com` on 28 Jun 2013 at 1:06

Attachments:
- [log.txt](https://storage.googleapis.com/google-code-attachments/socialauth-android/issue-52/comment-64/log.txt)

**Comment by GoogleCodeExporter** [comment]
```
I am having this same issue fbconnect// blah blah blah.... I am not a 
programmer and have no clue what to do... is this something that can be fixed 
by a end user because technical support at Straight talk - is only reading a 
frigging book and has no clue! 
```

Original comment by `star42...@yahoo.com` on 6 Jul 2013 at 9:53

**Comment by GoogleCodeExporter** [comment]
```
hi , this issue is already closed please open new issue if you are facing any 
problems.
```

Original comment by `vineet.a...@3pillarglobal.com` on 8 Jul 2013 at 5:50

**Comment by GoogleCodeExporter** [comment]
```
Hi Project member ,

    I was getting the authentication fail in FB with socialauth-android-2.0.jar in your custom Ui sample . so i used socialauth-android-2.1.jar , now FB is working fine but with twitter and linkedIn getting problem

 1. twitter -----> Could not connect using SocialAuth.
 2. linkedIn ----> org.brickred.socialauth.android.SocialAuthError: A secure      connection could not be established


Please see on this issue ........
```

Original comment by `ashun...@gmail.com` on 19 Jul 2013 at 1:15

**Comment by GoogleCodeExporter** [comment]
```
I keep getting the same problem with candy crush saga. Does anyone know how to 
fix this do that I could connect to Facebook n my friends 
```

Original comment by `d.f.lar...@gmail.com` on 6 Aug 2013 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
can anyone help me figure out how to play words free and other zynga games on 
my ph? i cant log in thru facebook 
```

Original comment by `IAMQUEE...@gmail.com` on 1 Oct 2013 at 8:28

**Comment by GoogleCodeExporter** [comment]
```
at 
fbconnect://success#access_token=CAACZAI5WgO4QBADjCOiAZAgpkzTRkwDDqslGqAztaGdkNv
l6z3Pp1HiNUUQeidTQUZCWfNC5za7ePP7V3bx8zAN06JSfTjdZB3DzfyTrBoJdPIQZA6xepZCIRHD1Wq
xv6jPtNf64nh7UZB68mUQUX6L68MALeGnxJwUI62EpkbH2H0gj5s3LkOcWBgxRjJnayLsE3wibWaZCAu
uTlwYAfR4s&expires_in=5132110.
```

Original comment by `IAMQUEE...@gmail.com` on 1 Oct 2013 at 8:31

**Comment by GoogleCodeExporter** [comment]
```
Hi vineet,

uploadImageAsync is throwing exception.

In library res = getCurrentProvider().uploadImage()

Is throwing exception org.brickred.socialauth.exception.SocialAuthException: 
java.io.IOException: Unexpected response code for CONNECT: 400.

Please resolve that issue i am wating for your response.
```

Original comment by `dear.vi...@gmail.com` on 11 Nov 2014 at 10:18

**Comment by GoogleCodeExporter** [comment]
```
Hi team,can you please suggest me my bug.i am using social auth android for 
facebook login in my application.But it is giving following error.

11-22 11:41:06.288: D/SocialAuthAdapter(16237): Loading keys and secrets from 
configuration
11-22 11:41:06.305: D/SocialAuthAdapter(16237): oauth_consumer.properties not 
found
11-22 11:41:06.306: D/SocialAuthAdapter(16237): Could not load configuration
11-22 11:41:06.308: D/SocialAuthAdapter(16237): Starting webview for 
authentication
11-22 11:41:06.338: D/SocialAuthError(16237): 
org.brickred.socialauth.exception.SocialAuthConfigurationException: SocialAuth 
configuration is null.
11-22 11:41:06.339: W/System.err(16237): 
org.brickred.socialauth.android.SocialAuthError: URL Authentication error
11-22 11:41:06.350: W/System.err(16237):    at 
org.brickred.socialauth.android.SocialAuthAdapter$4.run(SocialAuthAdapter.java:6
53)
11-22 11:41:06.350: W/System.err(16237):    at 
java.lang.Thread.run(Thread.java:838)

please suggest me what would be the wrong here and let me know what can i do??

```

Original comment by `malli.pu...@gmail.com` on 22 Nov 2014 at 6:26

**Comment by GoogleCodeExporter** [comment]
```
hello .. i want to navigate to another activity after authentication and want 
to logout from there. need sample code.

```

Original comment by `pal...@bugletech.com` on 26 Feb 2015 at 6:02

**Comment by GoogleCodeExporter** [comment]
```
Hi, I got the same error in webapp, I tried with multiply versions, including 
last version, But I always have same problem 'Verification code is null', I put 
right url in fb and goole, but the issue not resolved. What to do?
```

Original comment by `IHelthMa...@gmail.com` on 25 May 2015 at 7:53
